### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by willwoodward** [willwoodward/woodwork-meta#1]
### Description
Covers how to use, examples, licensing, contributing, roadmaps, issue templates and organisation.

### To-do
- [x] willwoodward/woodwork-engine#7
- [x] willwoodward/woodwork-engine#64
- [x] willwoodward/woodwork-engine#63
- [x] willwoodward/woodwork-engine#65
- [x] willwoodward/woodwork-engine#66
- [x] willwoodward/woodwork-engine#67
- [x] willwoodward/woodwork-engine#68
- [x] willwoodward/woodwork-engine#69
- [x] willwoodward/woodwork-website#2
