### ISSUE TITLE
Parsing

### ISSUE THREAD

**Issue by willwoodward** [willwoodward/woodwork-meta#3]
### Description
Mainly covers the parsing of woodwork-engine, rather than the Language Server for now.

### To-do
- [x] willwoodward/woodwork-engine#47
- [x] willwoodward/woodwork-engine#46
- [x] willwoodward/woodwork-engine#39
- [x] willwoodward/woodwork-engine#70
- [x] willwoodward/woodwork-engine#89
