### ISSUE TITLE
Developer Experience

### ISSUE THREAD

**Issue by willwoodward** [willwoodward/woodwork-meta#4]
### Description
Covers DX, like the language server usability, development environments and error messages.

### To-do
- [x] willwoodward/woodwork-engine#58
- [x] willwoodward/woodwork-engine#32
- [x] willwoodward/woodwork-language#3
