### ISSUE TITLE
DevOps Pipelines

### ISSUE THREAD

**Issue by willwoodward** [willwoodward/woodwork-meta#5]
### Description
Covers automated deployment and basic security settings.

### To-do
- [x] willwoodward/woodwork-engine#33
- [x] willwoodward/woodwork-engine#8
- [x] willwoodward/woodwork-engine#71
- [x] willwoodward/woodwork-language#4
- [x] willwoodward/woodwork-engine#77
