### ISSUE TITLE
Program Flow

### ISSUE THREAD

**Issue by willwoodward** [willwoodward/woodwork-meta#6]
### Description
Covers component interaction and task master execution.

### To-do
- [x] willwoodward/woodwork-engine#72
- [x] willwoodward/woodwork-engine#73
- [x] willwoodward/woodwork-engine#80
- [x] willwoodward/woodwork-engine#82
- [x] willwoodward/woodwork-engine#84
- [x] willwoodward/woodwork-engine#86
