### ISSUE TITLE
Component Development

### ISSUE THREAD

**Issue by willwoodward** [willwoodward/woodwork-meta#7]
### Description
Covers general development to woodwork-engine, specifically targeted around making components suitable for the MVP.

### To-do
- [x] willwoodward/woodwork-engine#62
- [x] willwoodward/woodwork-engine#53
- [x] willwoodward/woodwork-engine#38
- [x] willwoodward/woodwork-engine#24
- [x] willwoodward/woodwork-engine#74
- [x] willwoodward/woodwork-engine#76
- [x] willwoodward/woodwork-language#5
- [x] willwoodward/woodwork-engine#79
- [x] willwoodward/woodwork-engine#87
